//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apworks.Repositories.NHibernate.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apworks.Repositories.NHibernate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the NHibernate criteria from the given specification..
        /// </summary>
        internal static string EX_CREATE_CRITERIA_FROM_SPEC_FAIL {
            get {
                return ResourceManager.GetString("EX_CREATE_CRITERIA_FROM_SPEC_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the object from the database via NHibernate session..
        /// </summary>
        internal static string EX_DELETE_FAIL {
            get {
                return ResourceManager.GetString("EX_DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the required object from database via NHibernate session..
        /// </summary>
        internal static string EX_FIND_FAIL {
            get {
                return ResourceManager.GetString("EX_FIND_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find all the objects from database via NHibernate session..
        /// </summary>
        internal static string EX_FINDALL_FAIL {
            get {
                return ResourceManager.GetString("EX_FINDALL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get all the entities by specification. No entity can be found..
        /// </summary>
        internal static string EX_GETALL_FAIL {
            get {
                return ResourceManager.GetString("EX_GETALL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the object by key from database via NHibernate session..
        /// </summary>
        internal static string EX_GETBYKEY_FAIL {
            get {
                return ResourceManager.GetString("EX_GETBYKEY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the object by specification..
        /// </summary>
        internal static string EX_GETBYSPEC_FAIL {
            get {
                return ResourceManager.GetString("EX_GETBYSPEC_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize the NHibernate database session object..
        /// </summary>
        internal static string EX_INIT_NH_DBSESSION_FAIL {
            get {
                return ResourceManager.GetString("EX_INIT_NH_DBSESSION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type of Repository Context was assigned to NHibernate Repository implementation..
        /// </summary>
        internal static string EX_INVALID_CONTEXT_TYPE {
            get {
                return ResourceManager.GetString("EX_INVALID_CONTEXT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the NHibernate database session..
        /// </summary>
        internal static string EX_OPEN_NH_SESSION_FAIL {
            get {
                return ResourceManager.GetString("EX_OPEN_NH_SESSION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHibernate session failed to save the specified object..
        /// </summary>
        internal static string EX_SAVE_FAIL {
            get {
                return ResourceManager.GetString("EX_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the object in database via NHibernate session..
        /// </summary>
        internal static string EX_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("EX_UPDATE_FAIL", resourceCulture);
            }
        }
    }
}
